name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn 
    - name: list dir
      run: ls -la 
    - name:  check target folder
      run: |
        cd target/generated-docs
        ls -la
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v4
      with: 
       name: download pdf
       path: target/generated-docs/example-manual.pdf
